_format_version: "3.0"

services:
  - name: games-service
    url: http://games:4001
    routes:
      - name: games-routes
        paths:
          - /games
        strip_path: true
        methods:
          - GET
          - POST
          - OPTIONS
        plugins:
          - name: cors
            config:
              origins:
                - http://localhost:3000
              methods:
                - GET
                - POST
                - OPTIONS
              headers:
                - Accept
                - Accept-Version
                - Content-Length
                - Content-MD5
                - Content-Type
                - Date
                - X-Auth-Token
                - Authorization
              exposed_headers:
                - Content-Length
                - Content-Type
              credentials: false
              max_age: 3600
              preflight_continue: false
          - name: rate-limiting
            config:
              minute: 300
              hour: 5000
              limit_by: ip
              policy: local
              fault_tolerant: true
              hide_client_headers: false

  - name: wallets-service
    url: http://wallets:4002
    routes:
      - name: wallets-routes
        paths:
          - /wallets
        strip_path: true
        methods:
          - GET
          - POST
          - OPTIONS
        plugins:
          - name: cors
            config:
              origins:
                - http://localhost:3000
              methods:
                - GET
                - POST
                - OPTIONS
              headers:
                - Accept
                - Accept-Version
                - Content-Length
                - Content-MD5
                - Content-Type
                - Date
                - X-Auth-Token
                - Authorization
              exposed_headers:
                - Content-Length
                - Content-Type
              credentials: false
              max_age: 3600
              preflight_continue: false
          - name: rate-limiting
            config:
              minute: 120
              hour: 2000
              limit_by: ip
              policy: local
              fault_tolerant: true
              hide_client_headers: false
